-- Run this entirely in the Supabase SQL Editor

-- 1. Create the timeline_events table
create table public.timeline_events (
  id bigint generated by default as identity primary key,
  year text not null,
  title text not null,
  description text not null,
  image_url text, -- nullable, for future image links
  align text not null default 'left',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create daily_notes table
create table public.daily_notes (
  id bigint generated by default as identity primary key,
  content text not null,
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Insert some mock data for timeline_events so the site isn't empty
insert into public.timeline_events (year, title, description, align) values
('2017', 'Where It All Began', 'A chance encounter that sparked a connection we couldn''t ignore. The beginning of our shared story.', 'left'),
('2020', 'Building Our Home', 'Moving in together and turning a house into a home filled with endless laughter and a few burnt dinners.', 'right'),
('2023', 'The Next Chapter', 'A magical evening, a beautiful question, and the easiest ''Yes'' ever spoken. Engaged and ready for forever.', 'left'),
('2026', 'The Ultimate Celebration', 'December 10th. Surrounding ourselves with the people we love to celebrate the rest of our lives.', 'right');

-- 4. Insert initial daily note
insert into public.daily_notes (content) values
('As we continue building this capsule, everyday moments turn into lasting memories.');

-- 5. Enable Row Level Security (RLS)
alter table public.timeline_events enable row level security;
alter table public.daily_notes enable row level security;

-- 6. Create RLS Policies
-- We want anyone to be able to read the tables (so the timeline can be public or semi-private)
-- But only authenticated users can insert/update/delete.
create policy "Allow public read access to timeline_events" 
on public.timeline_events for select using (true);

create policy "Allow authenticated insert to timeline_events" 
on public.timeline_events for insert to authenticated with check (true);

create policy "Allow authenticated update to timeline_events" 
on public.timeline_events for update to authenticated using (true);

create policy "Allow authenticated delete to timeline_events" 
on public.timeline_events for delete to authenticated using (true);

-- Same for Daily Notes
create policy "Allow public read access to daily_notes" 
on public.daily_notes for select using (true);

create policy "Allow authenticated insert to daily_notes" 
on public.daily_notes for insert to authenticated with check (true);

create policy "Allow authenticated update to daily_notes" 
on public.daily_notes for update to authenticated using (true);

create policy "Allow authenticated delete to daily_notes" 
on public.daily_notes for delete to authenticated using (true);
