export const countryTranslations: Record<string, string> = {
  "United States of America": "ארצות הברית",
  "France": "צרפת",
  "Italy": "איטליה",
  "Spain": "ספרד",
  "United Kingdom": "בריטניה",
  "Germany": "גרמניה",
  "Greece": "יוון",
  "Thailand": "תאילנד",
  "Japan": "יפן",
  "China": "סין",
  "India": "הודו",
  "Brazil": "ברזיל",
  "Mexico": "מקסיקו",
  "Canada": "קנדה",
  "Australia": "אוסטרליה",
  "Vietnam": "וייטנאם",
  "Portugal": "פורטוגל",
  "Netherlands": "הולנד",
  "Switzerland": "שוויץ",
  "United Arab Emirates": "איחוד האמירויות",
  "Egypt": "מצרים",
  "South Africa": "דרום אפריקה",
  "Morocco": "מרוקו",
  "Argentina": "ארגנטינה",
  "Peru": "פרו",
  "Colombia": "קולומביה",
  "South Korea": "דרום קוריאה",
  "Indonesia": "אינדונזיה",
  "Philippines": "הפיליפינים",
  "Malaysia": "מלזיה",
  "Singapore": "סינגפור",
  "Turkey": "טורקיה",
  "Russia": "רוסיה",
  "Austria": "אוסטריה",
  "Belgium": "בלגיה",
  "Sweden": "שוודיה",
  "Norway": "נורווגיה",
  "Denmark": "דנמרק",
  "Finland": "פינלנד",
  "Ireland": "אירלנד",
  "Israel": "ישראל",
  "Poland": "פולין",
  "Czechia": "צ'כיה",
  "Hungary": "הונגריה",
  "Croatia": "קרואטיה",
  "Romania": "רומניה",
  "Bulgaria": "בולגריה",
  "Serbia": "סרביה",
  "Georgia": "גאורגיה",
  "Sri Lanka": "סרי לנקה",
  "Maldives": "האיים המלדיביים",
  "Seychelles": "איי סיישל",
  "Mauritius": "מאוריציוס",
  "New Zealand": "ניו זילנד",
  "Fiji": "פיג'י",
  "Cuba": "קובה",
  "Dominican Rep.": "הרפובליקה הדומיניקנית",
  "Bahamas": "איי בהאמה",
  "Jamaica": "ג'מייקה",
  "Puerto Rico": "פוארטו ריקו",
  "Costa Rica": "קוסטה ריקה",
  "Panama": "פנמה",
  "Chile": "צ'ילה",
  "Ecuador": "אקוודור",
  "Uruguay": "אורוגוואי",
  "Kenya": "קניה",
  "Tanzania": "טנזניה",
  "Madagascar": "מדגסקר",
  "Iran": "איראן",
  "Saudi Arabia": "ערב הסעודית",
  "Jordan": "ירדן",
  "Lebanon": "לבנון",
  "Cyprus": "קפריסין"
};

export function translateCountry(englishName: string): string {
  return countryTranslations[englishName] || englishName;
}

// Countries to exclude from rendering and the dropdown
export const BLOCKED_COUNTRIES = new Set([
  "Palestine",
  "Palestinian Territory",
  "West Bank",
]);

export function isBlockedCountry(name: string): boolean {
  return BLOCKED_COUNTRIES.has(name);
}
